version: '3'

services:
  server:
    container_name: tradersenshi-server 
    build:
      context: ./server
      dockerfile: Dockerfile
    image: server
    profiles: ["server", "dev"]
    environment:
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      DB_NAME: default
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    depends_on:
      - mongodb
      - redis

  mongodb:
    container_name: tradersenshi-mongodb
    image: mongo
    ports:
      - "27017:27017"

  redis:
    container_name: tradersenshi-redis
    image: redis
    ports:
      - "6379:6379"

  frontend:
    container_name: tradersenshi-client
    build:
      context: ./client
      dockerfile: Dockerfile
    profiles: ["frontend", "dev"]
    image: react
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
